#ifndef DEPTHTOUNITY_GLOBAL_H
#define DEPTHTOUNITY_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(DEPTHTOUNITY_LIBRARY)
#  define DEPTHTOUNITYSHARED_EXPORT Q_DECL_EXPORT
#else
#  define DEPTHTOUNITYSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // DEPTHTOUNITY_GLOBAL_H
